// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package magalucloud

import (
	"github.com/MagaluCloud/mgc-sdk-go/client"
	"github.com/MagaluCloud/mgc-sdk-go/compute"
	"github.com/MagaluCloud/mgc-sdk-go/objectstorage"
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName     *string                 `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType   *string                 `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion   *string                 `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug         *bool                   `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce         *bool                   `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError       *string                 `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars      map[string]string       `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars []string                `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	Token               *string                 `mapstructure:"token" cty:"token" hcl:"token"`
	AccessKey           *string                 `mapstructure:"access_key" cty:"access_key" hcl:"access_key"`
	SecretKey           *string                 `mapstructure:"secret_key" cty:"secret_key" hcl:"secret_key"`
	Region              *Region                 `mapstructure:"region" cty:"region" hcl:"region"`
	Bucket              *string                 `mapstructure:"bucket" cty:"bucket" hcl:"bucket"`
	Filename            *string                 `mapstructure:"filename" cty:"filename" hcl:"filename"`
	Expires             *string                 `mapstructure:"expires" cty:"expires" hcl:"expires"`
	URL                 *client.MgcUrl          `mapstructure:"url" cty:"url" hcl:"url"`
	Endpoint            *objectstorage.Endpoint `mapstructure:"endpoint" cty:"endpoint" hcl:"endpoint"`
	ImageName           *string                 `mapstructure:"image_name" cty:"image_name" hcl:"image_name"`
	Platform            *compute.Platform       `mapstructure:"platform" cty:"platform" hcl:"platform"`
	Architecture        *compute.Architecture   `mapstructure:"architecture" cty:"architecture" hcl:"architecture"`
	License             *compute.License        `mapstructure:"license" cty:"license" hcl:"license"`
	Version             *string                 `mapstructure:"version" cty:"version" hcl:"version"`
	Description         *string                 `mapstructure:"description" cty:"description" hcl:"description"`
	UEFI                *bool                   `mapstructure:"uefi" cty:"uefi" hcl:"uefi"`
	SkipCleanup         *bool                   `mapstructure:"skip_cleanup" cty:"skip_cleanup" hcl:"skip_cleanup"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"token":                      &hcldec.AttrSpec{Name: "token", Type: cty.String, Required: false},
		"access_key":                 &hcldec.AttrSpec{Name: "access_key", Type: cty.String, Required: false},
		"secret_key":                 &hcldec.AttrSpec{Name: "secret_key", Type: cty.String, Required: false},
		"region":                     &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"bucket":                     &hcldec.AttrSpec{Name: "bucket", Type: cty.String, Required: false},
		"filename":                   &hcldec.AttrSpec{Name: "filename", Type: cty.String, Required: false},
		"expires":                    &hcldec.AttrSpec{Name: "expires", Type: cty.String, Required: false},
		"url":                        &hcldec.AttrSpec{Name: "url", Type: cty.String, Required: false},
		"endpoint":                   &hcldec.AttrSpec{Name: "endpoint", Type: cty.String, Required: false},
		"image_name":                 &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"platform":                   &hcldec.AttrSpec{Name: "platform", Type: cty.String, Required: false},
		"architecture":               &hcldec.AttrSpec{Name: "architecture", Type: cty.String, Required: false},
		"license":                    &hcldec.AttrSpec{Name: "license", Type: cty.String, Required: false},
		"version":                    &hcldec.AttrSpec{Name: "version", Type: cty.String, Required: false},
		"description":                &hcldec.AttrSpec{Name: "description", Type: cty.String, Required: false},
		"uefi":                       &hcldec.AttrSpec{Name: "uefi", Type: cty.Bool, Required: false},
		"skip_cleanup":               &hcldec.AttrSpec{Name: "skip_cleanup", Type: cty.Bool, Required: false},
	}
	return s
}
