name: Notify Integration Release (Tag)
on:
  push:
    tags:
      - '*.*.*'
jobs:
  strip-version:
    runs-on: ubuntu-latest
    outputs:
      packer-version: ${{ steps.strip.outputs.packer-version }}
    steps:
      - name: Strip leading v from version tag
        id: strip
        env:
          REF: ${{ github.ref_name }}
        run: |
          echo "packer-version=$(echo "$REF" | sed -E 's/v?([0-9]+\.[0-9]+\.[0-9]+)/\1/')" >> "$GITHUB_OUTPUT"
  notify-release:
    needs:
      - strip-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
      - name: Setup Go Environment
        uses: actions/setup-go@v6
      - name: Generate Docs
        shell: bash
        run: make generate
      - name: Check Docs
        shell: bash
        run: |
          if [[ -z "$(git status -s)" ]]; then
            echo "OK"
          else
            echo "Docs have been updated, but the compiled docs have not been committed."
            echo "Run 'make generate', and commit the result to resolve this error."
            exit 1
          fi
      - name: Checkout integration-release-action
        uses: actions/checkout@v6
        with:
          repository: hashicorp/integration-release-action
          path: ./integration-release-action
      - name: Notify Release
        uses: ./integration-release-action
        with:
          integration_identifier: "packer/julianolf/magalucloud"
          release_version: ${{ needs.strip-version.outputs.packer-version }}
          release_sha: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
